name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          show-versioninfo: true
      - uses: julia-actions/cache@v2
      - name: Run torus wave smoke test
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
        env:
          TRIXI_TEST: wave_torus

  format-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/julia-format@v4
        with:
          version: "1.0.60"
